name: ConodiaJobs
version: 1.0.0
author: PandaGuerrier
main: fr.pandaguerrier.jobs.ConodiaJobs
depend: [ConodiaGameAPI, Factions]
commands:
  jobs:
    description: Permet d'ouvrir le menu principal.
    aliases: [job, jobs]
  conojreload:
    description: Permet de recharger le plugin.
    aliases: [conojr]
  levels:
    description: Permet de voir les niveaux des métiers.
    aliases: [level, lvl, levels, lvs]


  